import Link from "next/link";
import Head from "next/head";
import { IoTriangleOutline } from "react-icons/io5";

const Layout = ({ children, title = "Crypto Tracker" }) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <Link href="/" passHref>
          <a>
            <div className="Icon">
              <IoTriangleOutline />
              <p className="brand">Crypto Tracker</p>
            </div>
          </a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
